common: update fuse.h include
currently breaks build

system/core/sdcard/sdcard.c: In function 'handle_opendir':
system/core/sdcard/sdcard.c:1369:8: error: 'struct fuse_open_out' has no member named 'padding'

comes with pr #620 on kernel

Change-Id: I83b4d637781d27585694590d7bf86fb7562ef205
Signed-off-by: Erik Castricum <erikcas1972@gmail.com>