CommonConfig: Move FCM from system to product partition
Use new DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE which is
designed as a replacement of DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE.

Otherwise we will get a lot of such errors:
ERROR: HIDL interface * is referenced in
/system/etc/vintf/compatibility_matrix.device.xml, but
there is no corresponding .hal definition associated
with a hidl_interface module in this build. Typo?

Test: m check-vintf-all

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>