rootdir: Do not attempt to strip scripts
Without "strip: none", Android's build system will try to
optimize any cc_prebuilt_binary.

Since there's not much that llvm can do to further strip a
plaintext script, instruct it to restrain itself.

Fixes:
```
prebuilts/clang/host/linux-x86/clang-r353983c1/bin/llvm-strip: \
    error: 'device/sony/common/rootdir/vendor/bin/init.qcom.adspstart.sh': \
    The file was not recognized as a valid object file
```