etc: init: Rename init.usb.rc to usb.rc
Rename init.usb.rc to usb.rc so that it does not conflict
with the rc provided by the system.

error: device/sony/common/rootdir: MODULE.TARGET.ETC.init.usb.rc
already defined by system/core/rootdir.

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>