vintf: Bump device manifest version to 5
Google removed[1] the obsolete FCM 4 and the minimum required
version is now 5.

  ERROR: No such file or directory: Cannot find framework matrix
  at FCM version 4.: No such file or directory

[1] https://android.googlesource.com/platform/hardware/interfaces/+/7ad5797272c40c2b83b0df5a57a0f248a210091b

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>